---
- hosts: all
  become: yes
  become_method: sudo
  tasks:

  - name: "Set Instance ID Var"
    shell: ec2metadata --instance-id
    register: instance_id

  - name: "Show Instance ID"
    debug:
      msg: "My Instance ID is: {{ instance_id.stdout }}"
