---
- hosts: all
  become: yes
  become_method: sudo
  tasks:

  - name: "Set Instance ID Var"
    shell: ec2metadata --instance-id
    register: instance_id

  - ec2_instance_facts:
      instance_ids:
        - {{ instance_id.stdout }}

  - name: "Show Instance ID and other Facts Gathered"
    debug:
      msg: "My Instance ID is: {{ instance_id.stdout }}"
